{{- if .Values.crontabui.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crontabui
  labels:
    io.kompose.service: crontabui
  {{- include "dolidock.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.crontabui.replicas }}
  selector:
    matchLabels:
      io.kompose.service: crontabui
    {{- include "dolidock.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        io.kompose.network/dolidock-default: "true"
        io.kompose.service: crontabui
      {{- include "dolidock.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: BASIC_AUTH_USER
          valueFrom:
            secretKeyRef:
              key: crontabui-user
              name: dolistock
        - name: BASIC_AUTH_PWD
          valueFrom:
            secretKeyRef:
              key: crontabui-password
              name: dolistock
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.crontabui.image.repository }}:{{ .Values.crontabui.image.tag | default .Chart.AppVersion }}
        name: crontabui
        ports:
        - containerPort: 8000
        resources: {{- toYaml .Values.crontabui.resources | nindent 10 }}
        securityContext:
          runAsGroup: 0
          runAsUser: 0
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        - mountPath: /opt/cron
          name: crontabui-data
        {{- end }}
      imagePullSecrets: {{ .Values.imagePullSecrets | default list | toJson }}
      restartPolicy: Always
      {{- if .Values.persistence.enabled }}
      volumes:
      - name: crontabui-data
        persistentVolumeClaim:
          claimName: crontabui-data
      {{- end }}
{{- end -}}